config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  authenticated :user do
    root :to => "users#index"
  end
  unauthenticated :user do
    devise_scope :user do  
      get "/" => "devise/sessions#new"
    end 
  end 
  
  patch "apply", to: "users#apply"
  patch "join", to: "users#join"
  resources :home
  resources :users
  resources :teams
  resources :semesters

end

app/models/semester.rb
class Semester < ActiveRecord::Base
	validates :year, :presence =>true
	validates :season, :presence =>true
	has_many :teams
end

app/models/team.rb
class Team < ActiveRecord::Base
	validates :name, :presence =>true
	has_many :users
	belongs_to :semester
end

app/models/user.rb
class User < ActiveRecord::Base 
	# Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable

	devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :trackable, :validatable
	validates :email, :presence =>true
    validates :name, :presence =>true
	belongs_to :team
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:name, :email) }
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
  end

end

app/controllers/semesters_controller.rb
class SemestersController < ApplicationController
  def index()
    @semesters = Semester.all
  end	

 def show()
  	@semester = Semester.find(params[:id])
 end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index()
    @teams = Team.all
  end

  def show()
  	@team = Team.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index()
    render :index
  end

  def apply
	  @team = Team.find(params[:id])
    @user = current_user
  	@user.update_attribute(:team, @team)
  	@user.save
	  redirect_to '/'  	
  end	

  def join
    @semester = Semester.find(params[:id])
    @user = current_user
    @user.team.update_attribute(:semester, @semester)
    @user.team.save
    redirect_to '/'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/semesters_helper.rb
module SemestersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Final</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/semesters/_semester.html.erb
<td><%= link_to semester.season.concat(' ').concat(semester.year.to_s), semester %> </td>

app/views/semesters/index.html.erb
<div id='teams'>
<h1 id = 'allteams'> All Semesters </h1>
<div class="container">
  <div class="row">
    <h3>Semesters</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @semesters.each do |semester| %>
            <tr>
              <%= render semester %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
  </div>
  <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
</div>

app/views/semesters/show.html.erb
<h3 id='semester'>Semester</h3>
<p id = 'semester'><%= @semester.season if @semester.season %> <%= @semester.year if @semester.year %></p>
<div id='semester'>
<% if current_user.admin == true %>
	<%= button_to "Join Semester", join_path(id: @semester), :class => "button medium", :method => :patch %>
<%end%>
Team List<ul>
  <% Team.all.entries.each do |team|%>
    <% if team.semester == @semester %>
      <li><%= render team %></li>
    <% end %>
  <% end %>
</ul>
</div>
<br>
<div id='calendars'>
<% if @semester.season == 'Spring' %>
	<%= calendar(:year => @semester.year, :month => 3)%>
	<br>
	<%= calendar(:year => @semester.year, :month => 4)%>
	<br>
	<%= calendar(:year => @semester.year, :month => 5)%>
	<br>
	<%= calendar(:year => @semester.year, :month => 6)%>
	<br>
<% else %>
	<%= calendar(:year => @semester.year, :month => 9)%>
	<br>
	<%= calendar(:year => @semester.year, :month => 10)%>
	<br>
	<%= calendar(:year => @semester.year, :month => 11)%>
	<br>
	<%= calendar(:year => @semester.year, :month => 12)%>
	<br>
<% end %>
</div>

app/views/signup/index.html.erb
<h1>sup </h1>

app/views/users/index.html.erb
<div id='page'>

<h1>Hello, <%=current_user.name%>. </h1>

Name: <%=current_user.name%>
<br>
Email: <%=current_user.email%>
<br>
Team: <% if current_user.team %>
	<%= link_to current_user.team.name, current_user.team %>
	<% else %>
		<em> Not assigned to any team </em>
	<% end %>
<br>
<br>
<br>
<br>
<h3>
<%= link_to "All Teams", teams_path %>
<br>
<br>
<br>
<br>
<%= link_to "All Semesters", semesters_path %>
</h3>
<br>
<br>
<br>
<br>
<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>